### ISSUE TITLE
When a HyperV Host is running "empty" the Checks for Overcommitment, VM Health and Snapshots are returning a wrong unknown-message

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-hyperv#29]
Hello,

when a HyperV host is running "empty", because all of its VMs, snapshots etc. have been moved on purpose, the checks for Overcommitment, VM Health and Snapshots are returning the following unknown message:

```
[UNKNOWN]: Icinga Permission Error was thrown: : Hyper-V access denied
The user you are running this command with does not have permissions to access Hyper-V data on this host. Please add the user to the "Hyper-V Administrator" user group and restart the Icinga/PowerShell service afterwards
```

Is it possible to detect this case and still return an OK?

**Comment by K0nne** [comment]
Thanks for the bugfix. Unfortunately it doen't work as expected.
It solves the initial problem by returning:

```
[UNKNOWN]: Icinga Custom Error was thrown: Custom Exception: OK

Custom exception occured:
Everything is fine.
```

Unfortunately the checks stay in this state, even if the HyperV ressources are present again.
After I switched back to the current master, the checks went [OK] again.

**Comment by Yonas-net** [comment]
Hi, thanks that you have tested it but the PR is not ready.
