### ISSUE TITLE
Feature request: Invoke-IcingaCheckHyperVVMHealth - Add a threshold for the number of VMs in a cluster, which are not active (running)

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-hyperv#34]
Hello,

it whould be very helpful to have a threshold for the number of VMs in a cluster, which are not in an active state. 
Something like `Invoke-IcingaCheckHyperVVMHealth -ActiveVMs -CriticalActiveVMs 10`
This is an indication for hidden problems.

Thank you very much. The HyperV checks are already very helpful.

**Comment by LordHepipud** [comment]
Hello,

can you please test the linked PR for this? The `-ActiveVMs` argument is not required, just `-WarningActiveVms` and `-CriticalActiveVms`

**Comment by K0nne** [comment]
The PR is working great 💯 

**icinga { invoke-icingacheckhypervvmhealth -warningactivevms 28: -noperfdata}**
```
[WARNING] Virtual Computers: 1 Warning 27 Ok [WARNING] Active VMs (25)
\_ [WARNING] Active VMs: 25 is lower than threshold 28
1
```

**icinga { invoke-icingacheckhypervvmhealth -warningactivevms 28: -criticalactivevms 27: -noperfdata}**
```
[CRITICAL] Virtual Computers: 1 Critical 27 Ok [CRITICAL] Active VMs (25)
\_ [CRITICAL] Active VMs: 25 is lower than threshold 27
2
```
