### ISSUE TITLE
Feature Request - monitoring of the host status from the view of the virtual machine manager

### ISSUE THREAD

**Issue by K0nne** [Icinga/icinga-powershell-hyperv#40]
Hello,

we need to monitor the host status from the view of the hyperv virtual machine manager. we want to know if a host is in a state like Needs Attention, Not Responding, or Access Denied:

https://docs.microsoft.com/en-us/troubleshoot/system-center/vmm/troubleshoot-host-status-errors
https://docs.microsoft.com/en-us/powershell/module/virtualmachinemanager/get-scvmhost?view=systemcenter-ps-2019

This can be archieved by using the following command:

Get-SCVMHost -vmmserver "%vmm_hostname%" | select-object computername, overallstate

```
ComputerName      OverallState
------------      ------------
%hyperv_host1%              OK
%hyperv_host2%  NeedsAttention
```

**Comment by K0nne** [comment]
Are there any news on this topic?

**Comment by LordHepipud** [comment]
Yes, we are working on this plugin and will provide a test version as soon as possible :)

**Comment by LordHepipud** [comment]
Can you please test the linked PR? The plugin should be ready now.

**Comment by K0nne** [comment]
That's  awesome 🥳

**Comment by LordHepipud** [comment]
Hello,

any update on this? This is the last pending item for releasing v1.1.0 😁

**Comment by LordHepipud** [comment]
Hello,

did you had the chance to test the plugin already? The next release is still depending on the feedback of this.

Thank you in advance!

**Comment by LordHepipud** [comment]
Hello,

is there an update on this? Does the plugin work?

**Comment by K0nne** [comment]
Hello,
We still have to test it. There were some problems on our side. I will try to get the results this week. Sorry for the delay!

Am 25. Jan. 2022, 14:57, um 14:57, Lord Hepipud ***@***.***> schrieb:
>Hello,
>
>is there an update on this? Does the plugin work?
>
>--
>Reply to this email directly or view it on GitHub:
>https://github.com/Icinga/icinga-powershell-hyperv/issues/40#issuecomment-1021208166
>You are receiving this because you authored the thread.
>
>Message ID:
***@***.***>

**Comment by K0nne** [comment]
Hello! There were some problems on our side. I will test it this week. Sorry for the delay!
